AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-challenge

  Sample SAM Template for cloud-resume-challenge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName:  cloud-resume-challenge
      CodeUri: get-function/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get
            Method: get

  PutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName:  cloud-resume-challenge
      CodeUri: put-function/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /put
            Method: get

  ResumeSite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: resume-test.philward.io
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "https://resume-test.philward.io"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ResumeBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: OAIAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt DistributionOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Join
              -  ""
              -  -  "arn:aws:s3:::"
                 -  !Ref ResumeSite
                 -  /*
      Bucket: !Ref ResumeSite

  ResumeRoute53Record:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: Z05294393DFAN1FAG0KAE
      RecordSets:
        - Name: resume-test.philward.io
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt ResumeDistribution.DomainName

  ResumeCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: resume-test.philward.io
      DomainValidationOptions:
            - DomainName: resume-test.philward.io
              HostedZoneId: Z05294393DFAN1FAG0KAE
      ValidationMethod: DNS

  ResumeDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref ResumeCertificate
          SslSupportMethod: sni-only
        Aliases:
          - resume-test.philward.io
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: resume-test
          ForwardedValues:
            QueryString: false
        Origins:
          - DomainName: resume-test.philward.io.s3.us-east-1.amazonaws.com
            Id: resume-test
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [ "", [ "origin-access-identity/cloudfront/", !Ref DistributionOAI ] ]
        Enabled:  true
        DefaultRootObject:  resume.html

  DistributionOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for Resume Site"

  ViewCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-challenge
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName:  "ID"
          AttributeType:  "S"
      KeySchema:
        - AttributeName:  "ID"
          KeyType:  "HASH"



#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
