name: main
on: push
env:
  NODE_VERSION: 16
jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::806593901912:role/GithubActionsRole
          aws-region: us-east-1
      - name: Install dependencies
        run: yarn
      - name: test get-function
        run: cd /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/get-function && npm test ./
      - name: test put-function
        run: cd /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/put-function && npm test ./
