name: main
on: push
env:
  NODE_VERSION: 16
jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: test get-function
        run: cd /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/get-function && npm test ./
      - name: test put-function
        run: cd /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/put-function && npm test ./
