name: main
on: push
env:
  NODE_VERSION: 16
jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: test get-function
        run: cd /home/runner/work/cloud-resume-challenge/get_function && npm test ./
      - name: test put-function
        run: cd /home/runner/work/cloud-resume-challenge/put_function && npm test ./

  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/

  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET:  resume-test.philward.io
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: /home/runner/work/cloud-resume-challenge/cloud-resume-challenge/resume-site
